import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Payment for Partii.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Payment for <a href="https://partii.app">Partii.App!</a>
        </h1>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <Image src="/images/logo.png" width={400} height={400} />
            <p>Lorem ipsum 1</p>
          </a>
          <a href="" className={styles.card}>
            <Image src="/images/logo.png" width={400} height={400} />
            <p>Lorem ipsum 2</p>
          </a>
        </div>
      </main>

    </div>
  )
}
